from __future__ import annotations

from typing import Protocol
from uuid import UUID

from app.domain.models import (
    AgentEvent,
    ConfirmedMappingSet,
    DatasetRole,
    MatchResult,
    MatchConflict,
    NaturalLanguagePolicyProposal,
    NearMatchAnalysis,
    NearMatchReconciliationSummary,
    ReconciliationPolicy,
    ReconciliationListItem,
    ReconciliationSession,
    ReconciliationSummary,
    ToleranceReconciliationSummary,
    SchemaMappingProposal,
    SessionStatus,
    UploadedFile,
    CopilotMessage,
    SemanticClassification,
    ClientProfile,
    PatternSuggestion,
    ReusableRuleVersion,
    RuleExecution,
    ExportRecord,
    AIInvestigationRecord,
)


class ReconciliationRepository(Protocol):
    def initialize(self) -> None: ...
    def create(self, session: ReconciliationSession) -> ReconciliationSession: ...
    def get(self, reconciliation_id: UUID) -> ReconciliationSession | None: ...
    def list_sessions(self) -> list[ReconciliationListItem]: ...
    def save_file(self, reconciliation_id: UUID, file: UploadedFile) -> None: ...
    def save_mapping_proposal(
        self,
        reconciliation_id: UUID,
        proposal: SchemaMappingProposal,
        workflow_thread_id: str,
    ) -> None: ...
    def save_confirmed_mapping(
        self, reconciliation_id: UUID, mapping: ConfirmedMappingSet
    ) -> None: ...
    def save_policy_proposal(self, reconciliation_id: UUID, proposal: NaturalLanguagePolicyProposal, workflow_thread_id: str) -> None: ...
    def save_confirmed_policy(self, reconciliation_id: UUID, policy: ReconciliationPolicy) -> None: ...
    def update_status(self, reconciliation_id: UUID, status: SessionStatus) -> None: ...
    def save_results(
        self,
        reconciliation_id: UUID,
        matches: list[MatchResult],
        summary: ReconciliationSummary,
    ) -> None: ...
    def list_match_results(self, reconciliation_id: UUID) -> list[MatchResult]: ...
    def save_tolerance_results(self, reconciliation_id: UUID, matches: list[MatchResult], conflicts: list[MatchConflict], summary: ToleranceReconciliationSummary) -> None: ...
    def list_conflicts(self, reconciliation_id: UUID) -> list[MatchConflict]: ...
    def save_near_analysis(self, reconciliation_id: UUID, analysis: NearMatchAnalysis, workflow_thread_id: str, summary: NearMatchReconciliationSummary) -> None: ...
    def save_near_state(self, reconciliation_id: UUID, analysis: NearMatchAnalysis, matches: list[MatchResult], summary: NearMatchReconciliationSummary) -> None: ...
    def save_near_bulk_approval(self, reconciliation_id: UUID, analysis: NearMatchAnalysis, matches: list[MatchResult], summary: NearMatchReconciliationSummary, events: list[AgentEvent]) -> None: ...
    def add_event(self, event: AgentEvent) -> None: ...
    def list_events(self, reconciliation_id: UUID, limit: int = 50) -> list[AgentEvent]: ...
    def save_semantic_classification(self, classification: SemanticClassification) -> None: ...
    def list_semantic_classifications(self, reconciliation_id: UUID) -> list[SemanticClassification]: ...
    def save_copilot_message(self, message: CopilotMessage) -> None: ...
    def list_copilot_messages(self, reconciliation_id: UUID | None, conversation_id: UUID, limit: int = 40) -> list[CopilotMessage]: ...
    def save_human_selected_match(self, reconciliation_id: UUID, match: MatchResult, summary: NearMatchReconciliationSummary, analysis: NearMatchAnalysis) -> None: ...
    def save_client_profile(self, profile: ClientProfile) -> None: ...
    def get_client_profile(self, profile_id: UUID) -> ClientProfile | None: ...
    def list_client_profiles(self) -> list[ClientProfile]: ...
    def attach_profile(self, reconciliation_id: UUID, profile_id: UUID, version: int) -> None: ...
    def save_rule_version(self, rule: ReusableRuleVersion) -> None: ...
    def delete_rule(self, rule_id: str) -> None: ...
    def get_rule(self, rule_id: str, version: int | None = None) -> ReusableRuleVersion | None: ...
    def list_rules(self, profile_id: UUID | None = None) -> list[ReusableRuleVersion]: ...
    def list_active_rules(self, profile_id: UUID) -> list[ReusableRuleVersion]: ...
    def list_rule_history(self, rule_id: str) -> list[ReusableRuleVersion]: ...
    def save_pattern_suggestion(self, suggestion: PatternSuggestion) -> PatternSuggestion: ...
    def list_pattern_suggestions(self, reconciliation_id: UUID) -> list[PatternSuggestion]: ...
    def save_rule_execution(self, execution: RuleExecution) -> None: ...
    def list_rule_executions(self, reconciliation_id: UUID) -> list[RuleExecution]: ...
    def save_export(self, record: ExportRecord) -> None: ...
    def list_exports(self, reconciliation_id: UUID) -> list[ExportRecord]: ...
    def get_export(self, export_id: UUID) -> ExportRecord | None: ...
    def save_ai_investigation(self, investigation: AIInvestigationRecord) -> None: ...
    def list_ai_investigations(self, reconciliation_id: UUID, record_id: str) -> list[AIInvestigationRecord]: ...
